version: '3.7'

services:
  database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=farfalle
      - POSTGRES_PASSWORD=DynoveKoreniJeDynovymKorenimZivota
    volumes:
      - database-storage:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432

  admin:
    image: adminer:4.8.1
    networks:
      - backend
    ports:
      - 8089:8080

  api:
    container_name: farfalle_api
    image: farfalle_api:1.0.0
    build: ./backend
    networks:
      - backend
      - frontend
    ports:
      - 3001:3001

  app:
    container_name: farfalle_app
    image: farfalle_app:1.0.0
    build: ./frontend
    networks:
      - frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=http://api:3001/
  
volumes:
  database-storage:

networks:
  backend:
  frontend:
